### ISSUE TITLE
Report a possible silent misconfiguration in your repository

### ISSUE THREAD

**Issue by JialuZhang** [ndunks/fiberhome-AN5506-04F-#1]
In your file, https://github.com/ndunks/fiberhome-AN5506-04F-/blob/397353917fccf82215cf8a377076cfaa5e59d6ce/filesystem/fh/extend/vsftpd.conf

At line 43: idle_session_timeout = 600

This setting itself is a misconfiguration and adding it to your system will not change any system misbehavior.

Root cause: “data_connection_timeout” has the system preset default value, 300. The configuration “idle_session_timeout” has no effect if user does not set “data_connection_timeout” to less than or equal to zero.

Here is the VSFTPD source code to support this. To enable the configuration parameter "idle_session_timeout", user has to explicitly set another configuration parameter "data_connection_timeout" less than 0.

if (tunable_data_connection_timeout > 0) 
    {vsf_sysutil_set_alarm(tunable_data_connection_timeout);}
else if (tunable_idle_session_timeout > 0)
    {vsf_sysutil_clear_alarm();}

**Comment by ndunks** [comment]
Ah yes thankyou I for your help. So it need to set data timeout too. did you just play with the device or trying making custom firmware?

**Comment by JialuZhang** [comment]
Thank you so much for your nice and affirmative reply!
We are a group of researchers from Yale University building a tool for automatically detecting silent misconfigurations. 
Your reply confirms the usefulness of our tool.
Highly appreciated that!
